config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "fishings#index"
  resources :fishings do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

# Association
  belongs_to :user
  belongs_to :fishing

# validation
  validates :text, presence: true

end

app/models/fishing.rb
class Fishing < ApplicationRecord

  # validation
  with_options presence: true do
    validates  :title
    validates  :catch_copy
    validates  :concept
    validates  :image
  end

  # Association
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  def self.search(search)
    if search != ""
      Fishing.where('title LIKE(?)', "%#{search}%")
    else
      Fishing.all
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord

  # Association
  belongs_to :user
  belongs_to :fishing
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# validation
  with_options presence: true do
    validates :name
    validates :rod
    validates :reel
    validates :feed
  end

# Association
  has_many :fishings
  has_many :comments
  has_many :likes
  has_many :favorites, through: :likes, source: :fishing

  def like_this(clicked_fishing)
    self.likes.find_or_create_by(fishing: clicked_fishing)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:show, :index, :search]
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:rod,:reel,:feed])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


def create
  @comment = Comment.new(comment_params)
  if @comment.save
    redirect_to fishing_path(@comment.fishing)
  else
    @fishing = @comment.fishing
    @comments = @fishing.comments
    render "fishings/show"
  end
end


private
def comment_params
  params.require(:comment).permit(:text).merge(user_id: current_user.id, fishing_id: params[:fishing_id])
end


end

app/controllers/fishings_controller.rb
class FishingsController < ApplicationController

  def index
    @fishing = Fishing.includes(:user).order("created_at DESC").page(params[:page]).per(9)
  end

  def new
    @fishing = Fishing.new
  end

  def show
    @fishing = Fishing.find(params[:id])
    @comment = Comment.new
    @comments = @fishing.comments.includes(:user)
  end

  def create
    @fishing = Fishing.new(fishing_params)
  if
    @fishing.save
    redirect_to root_path
  else
    render :new
  end
  end

  def edit
    @fishing = Fishing.find(params[:id])
    if current_user != @fishing.user
      redirect_to action: :index
    end
  end

  def update
    @fishing = Fishing.find(params[:id])
    if @fishing.update(fishing_params)
      redirect_to action: "show"
    else
      render :edit
    end
  end

  def destroy
    fishing = Fishing.find(params[:id])
    fishing.destroy
    redirect_to root_path
  end

  def search
    @fishings = Fishing.search(params[:keyword])
  end


  private
  def fishing_params
    params.require(:fishing).permit(:title,:catch_copy,:concept,:image).merge(user_id: current_user.id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    current_user.like_this(clicked_fishing)
    flash[:success] = '投稿に「いいね！」しました。'
    redirect_back(fallback_location: root_path)
    # 前回の記事からelse以下の記述は削除
  end

  # ↓前回の記事からここを追記！
  def destroy
    current_user.likes.find_by(fishing_id: params[:fishing_id]).destroy
    flash[:danger] = '「いいね！」を解除しました。'
    redirect_back(fallback_location: root_path)
  end


  private

  def clicked_fishing
    Fishing.find(params[:fishing_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fishings_helper.rb
module FishingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fishings/_fishing.html.erb
<div class="card">
  <%= link_to image_tag(fishing.image, class: :card__img ),  fishing_path(fishing.id)%>
  <div class="card__body">
    <%= link_to fishing.title, fishing_path(fishing.id), class: :card__title%>
    <p class="card__summary">
      <%= fishing.catch_copy %>
    </p>
    <%= link_to "angler #{fishing.user.name} ", fishing_path(fishing.id), class: :card__user %>
    <div class=“fishing-date">
      <!-- 投稿した時刻を出力する -->
      <%= l fishing.created_at %>
    </div>
  </div>
</div>

app/views/fishings/_form.html.erb
<%= form_with model: @fishing, local: true do |f|%>
  <div class="field">
    <%= f.label :image, "魚の画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>
  
  <div id="image-list"></div>

  <div class="field">
    <%= f.label :title, "魚の名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "釣った場所" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "釣った餌（ルアー）" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>


  <div class="actions">
    <%= f.submit "登録", class: :form__btn  %>
  </div>
<% end %>

app/views/fishings/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集</h2>
      
      <%= render partial: "form",locals: { fishing: @fishing } %>
    </div>
  </div>
</div>

app/views/fishings/index.html.erb
<main class="main">
  <div class="inner">
  <div class="tooking">
    <%= "釣果を投稿しよう！" %>
    </div>
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "WELCOM!" %>
        <%= link_to "#{current_user.name}", user_path(current_user.id), class: :greeting__link%>
      </div> 
      <% end %>
    <div class="card__wrapper">
      <%= render partial: 'fishing', collection: @fishing %>
    </div>
    <%= paginate @fishing %>
  </div>
</main>

app/views/fishings/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        
        <%= render partial: "form",locals: { fishing: @fishing } %>
    </div>
  </div>
</div>

app/views/fishings/search.html.erb
<main class="main">
  <div class="inner">
    <div class="searching">
        <%= "検索結果" %>
    </div>
  <div class="contents_row">
  <% @fishings.each do |fishing| %>
    <%= render partial: "fishing", locals: { fishing: fishing } %>
  <% end %>
  </div>
</div>
</main>

app/views/fishings/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @fishing.title%>
      </p>
      <%= link_to "#{@fishing.user.name}", user_path(@fishing.user.id), class: :prototype__user %>
      <div class="prototype__image">
        <%= image_tag @fishing.image %>
      </div>
       <!-- いいね！ボタン -->
<div class="iine">
    <div>
      <!-- すでに「いいね！」されている時の表示 -->
      <% if user_signed_in?  %>
      <% if current_user.favorites.include?(@fishing) %>     
        <%= form_with(model: @like, url: like_path(id: @fishing.id), local: true, method: :delete) do |f| %>
          <%= f.hidden_field :fishing_id, value: @fishing.id %>
          <%= f.submit 'いいね！解除' %>
          <%= @fishing.likes.count %>
        <% end %>
      <% else %>

　　　　　<!-- まだ「いいね！」していない時の表示 -->
        <%= form_with(model: @like, url: likes_path, local: true) do |f| %>
          <%= f.hidden_field :fishing_id, value: @fishing.id %>
          <%= f.submit 'いいね！' %>
          <%= @fishing.likes.count %>
        <% end %>
      <% end %>
      <% end %>      
    </div>
</div>
      <% if user_signed_in? && current_user.id == @fishing.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集", edit_fishing_path(@fishing.id), class: :prototype__btn %>
          <%= link_to "削除", fishing_path(@fishing.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">釣果場所</p>
          <p class="detail__message">
            <%= @fishing.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">釣果の餌（ルアー）</p>
          <p class="detail__message">
            <%= @fishing.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@fishing,@comment],local: true do |f|%>
            <div class="field">
              <%= f.label :text, "✨釣果の感想、魚料理をコメントしよう✨" %><br />
              <%= f.text_area :text, id:"comment_content" ,size: 100%>
            </div>
            <div class="actions">
              <%= f.submit "投稿する", class: :form__btn  %>
            </div>
          <% end %>
          <% end %>
        <ul class="comments_lists">
          
          <% @comments.each do |comment| %>
            <li class="comments_list">
            <%= safe_join("#{comment.text}".split("\n"),tag(:br)) %>
              <%= link_to "投稿者 #{comment.user.name}", "/users/#{comment.user_id}", class: :comment_user %>
            </li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FISHING</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("fish65978.png", class: :logo), root_path %>
              <%= form_with(url: search_fishings_path, local: true, method: :get, class: "search-form") do |form| %>
              <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
              <%= form.submit "検索", class: "search-btn" %>
              <% end %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "新規投稿", new_fishing_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%end%>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © fishing All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "アングラー プロフィール"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">アングラー 名</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">メイン ロッド</th>
            <td class="table__col2"><%= @user.rod %></td>
          </tr>
          <tr>
            <th class="table__col1">メイン リール</th>
            <td class="table__col2"><%= @user.reel %></td>
          </tr>
          <tr>
            <th class="table__col1">オススメ ルアー（餌）</th>
            <td class="table__col2"><%= @user.feed %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの釣果"%>
      </h2>
      <div class="user__card">
        <%= render partial: "fishings/fishing", collection: @user.fishings %>
      </div>
    </div>
  </div>
</div>